# Generated by Django 3.0.5 on 2020-12-14 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201213_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 14, 14, 11, 35, 413463)),
        ),
    ]
