# Generated by Django 3.0.5 on 2020-12-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20201214_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
